Re-factor cgm-rg
Welthungerhilfe/cgm-rg pull request #67
Opened 2021-05-10 07:37 UTC by prajurock

- Aggregation added as Result Generation  Class

2021-05-10 11:53 UTC, prajurock commented
Tests are failing because there are lots of change in class. Please suggest any suggestion which you all have to improve the code. After implementing your suggestion I will fix the tests.

2021-05-10 12:06 UTC, markus-hinsche reviewed
Looks great for me, because achieves to reduce code duplication. 
I do not understand why 2 tests have been removed

2021-05-12 15:13 UTC, prashant905 commented
@prajurock  we are experiencing some code deletion due to refactoring. We are trying to put that piece of code back into develop branch.  Please don't merge any refactor code into develop branch until the issue is resolved.

2021-05-14 06:18 UTC, prajurock commented on src/result_generation/result_generation.py
> +class ResultGeneration:
Yes

2021-05-14 14:17 UTC, markus-hinsche approved these changes
LGTM

2021-05-14 15:19 UTC, shanky0009 approved these changes

2021-05-15 08:11 UTC, gangooteli commented
This code is failing for RGBD models. Found it while reviewing and also verified it locally.

![image](https://user-images.githubusercontent.com/24511086/118353228-f7a39180-b582-11eb-886b-c897a569b088.png)

**Suggestions to Everyone:** 

- Please run it locally before submitting any code for review (atleast for such large changes).
- Try to make refactoring as small as possible in a single PR. In some of the previous PR also, saw some huge changes in the code in a single PR.
- In this refactoring, I am able to see changes in 17 files, which is hard to review and find mistakes. 
- It can only be found if gone through whole code. 
- Reviewers, Pls take your time to review the code.

2021-05-15 08:12 UTC, gangooteli requested changes
Added comment, pls fix issues of RGBD model before merge.

2021-05-17 06:53 UTC, gangooteli requested changes

2021-05-17 06:53 UTC, gangooteli commented on src/result_gen_with_api.py
> +            result_generation,
Make changes in line 300 also where RGBD class is being used

2021-05-17 07:13 UTC, merged