Cgm 1312 versioning
Welthungerhilfe/cgm-rg pull request #80
Opened 2021-05-21 09:52 UTC by fooni

2021-05-26 07:22 UTC, gangooteli requested changes
cgm-rg does not have main branch. Should we use develop branch instead of main?

2021-05-26 07:22 UTC, gangooteli commented on README.md
> +after a merge to the `main` branch.
cgm-rg doesn't have a main branch.

2021-05-26 07:22 UTC, gangooteli commented on ci/azure-pipelines.yml
> +    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
cgm-rg does not have a main branch

2021-05-26 07:22 UTC, gangooteli commented on ci/azure-pipelines.yml
> +              git push --follow-tags origin HEAD:main
cgm-rg doesn't have a main branch

2021-05-26 08:33 UTC, gangooteli approved these changes
LGTM. 
Also renamed develop branch to main branch

2021-05-27 06:47 UTC, shanky0009 approved these changes

2021-05-27 06:49 UTC, merged